apiVersion: v1
kind: ConfigMap
metadata:
  name: &app-name go-fraud-cm
  namespace: test-a
  labels:
    app: *app-name
data:
  VERSION: "1.0"
  POD_NAME: "go-fraud"
  GRPC_HOST: ":50052"
  OTEL_EXPORTER_OTLP_ENDPOINT: "arch-eks-02-xray-collector.default.svc.cluster.local:4317"
  SAGEMAKER_ENDPOINT: "xgboost-serverless-ep-fraud-v22024-04-02-23-27-14"