apiVersion: v1
kind: Service
metadata:
  name: &app-name svc-go-fraud
  namespace: test-b
  labels:
    app: *app-name
spec:
  clusterIP: None
  ports:
  - port: 50052
    targetPort: 50052
    protocol: TCP
  selector:
    app: go-fraud