apiVersion: v1
kind: ConfigMap
metadata:
  name: &app-name go-fraud-cm
  namespace: test-a
  labels:
    app: *app-name
data:
  API_VERSION: "2.1-tls"
  POD_NAME: "go-fraud.k8"
  GRPC_HOST: ":50052"
  OTEL_EXPORTER_OTLP_ENDPOINT: "arch-eks-02-xray-collector.default.svc.cluster.local:4317"
  SAGEMAKER_ENDPOINT: "xgboost-serverless-ep-fraud-model-v3-2024-04-23-00-41-40"
  TLS: "true"